### ISSUE TITLE
比赛后台-规则-比赛颁奖：增加O组别统计选项

### ISSUE THREAD

**Issue by CuberKangChen** [CubingChina/cubingchina#173]
增加O组别统计选项，最好是年纪给到主办方自己填写，如果实现不了则可以先新增O25、O30、O35、O45等常见组别

**Comment by CuberKangChen** [comment]
> ![image](https://github.com/user-attachments/assets/ea71346e-0069-4650-b7d1-410728803bee)
> 
> 是否满足要求

前台规则页已满足，后台编辑页面也没问题的话这个需求就解决了

**Comment by guojia99** [comment]
![image](https://github.com/user-attachments/assets/3ceea38c-2462-4f90-9f70-619182369f60)
![image](https://github.com/user-attachments/assets/3591c6f5-fa8e-4b08-9754-2f8b054204e1)
后台界面如下后台数据修改没问题了，晚些时候我测试完所有地方，再pr上来

**Comment by guojia99** [comment]
![image](https://github.com/user-attachments/assets/c101a132-ffce-4bba-951a-a6be14d32cde)
使用逗号分割即可

**Comment by guojia99** [comment]
#174
