### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by MatteoColombo** [CubingChina/cubingchina#2]
Hi, 
I'm trying to clone the website on my server, I managed to install it, but nothing works, is it normal?
The website every links in the menu redirects to a 404 page.
Is the installation file updated? Do I have to move manually move any file? (e.g. files in /protected/view?)

Thank you

**Comment by Baiqiang** [comment]
Hi Matteo,
I'm sorry I forgot to put the rewrite rule in the readme. Did you try to port every 404 request to the index.php? For example, if you're using nginx, please add the following rules to the configuration file.
```nginx
    location / {
        if (!-e $request_filename) {
            rewrite ^/(.+)$ /index.php last;
        }
    }
```

**Comment by mehdiroshan** [comment]
Hi ,
I got the following error to install wampp.

CDbException
CDbConnection failed to open the DB connection.



What should be done?
Thank you

**Comment by Baiqiang** [comment]
@mehdiroshan Did you follow the step 3 and create the databases and mysql user for the application? Or you can edit the DB config here: https://github.com/CubingChina/cubingchina/blob/master/protected%2Fconfig%2Fmain.php#L98-L117

**Comment by mehdiroshan** [comment]
I installed the cubingchina

آHi,
I installed the program, but in this case show.
What should I do?
Please help I install applications on websites.

Thanks.
